package space.privatecanvas.app

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

val LocalUiLanguage = staticCompositionLocalOf { UiLanguage.English }

private val chineseUi = mapOf(
    "Back to contacts" to "返回联系人",
    "Session details" to "会话详情",
    "2 LIVE" to "2 人在线",
    "CONTACT ADDED" to "联系人已添加",
    "SECURE EXPORT SERVICE NOT CONNECTED" to "安全导出服务尚未连接",
    "DRAFT SAVED LOCALLY" to "草稿已保存在本机",
    "DRAFT DISCARDED" to "草稿已丢弃",
    "HIDDEN INPUT REVEALED" to "隐藏输入已公开",
    "UNDO" to "撤销",
    "DELETE" to "删除",
    "DISPLAY NAME UPDATED" to "显示名称已更新",
    "CONTACT DELETED" to "联系人已删除",
    "OFFLINE EDITING" to "离线编辑",
    "Start writing…" to "开始输入…",
    "Move block" to "移动气泡",
    "Unpin block" to "取消固定",
    "Pin block" to "固定气泡",
    "Merge unavailable offline" to "离线时不可合并",
    "Merge block" to "合并气泡",
    "Delete block" to "删除气泡",
    "Insert emoji" to "插入表情",
    "Create block" to "添加气泡",
    "Hidden input" to "隐藏输入",
    "Canvas overview" to "画布总览",
    "More actions" to "更多操作",
    "CANVAS ACTIONS" to "画布操作",
    "MERGE" to "合并",
    "HIDE INPUT" to "隐藏输入",
    "DELETE" to "删除",
    "EXPORT SPACE" to "导出空间",
    "APPEARANCE" to "外观",
    "Select a block first" to "请先选择一个气泡",
    "Confirmation required" to "需要确认",
    "Unavailable during offline editing" to "离线编辑时不可用",
    "Encrypted archive, PDF or image" to "加密归档、PDF 或图片",
    "Local theme and privacy" to "本机主题与隐私",
    "DELETE THIS BLOCK?" to "删除这个气泡？",
    "DELETE THIS BLOCK" to "删除这个气泡",
    "The block can be restored from the short undo action. Concurrent offline text is recovered into a separate block." to "删除后可在短时间内撤销；并发的离线文字会恢复到独立气泡中。",
    "CONFLICT RECOVERED" to "检测到删除冲突，已恢复为独立气泡",
    "CONTACT RENAMED" to "联系人名称已更新",
    "CONTACT PINNED" to "联系人已置顶",
    "CONTACT UNPINNED" to "已取消置顶联系人",
    "CONTACT NOT DELETED" to "联系人未删除",
    "SET A DEVICE SCREEN LOCK FIRST" to "请先设置设备屏幕锁",
    "CONTACT BLOCKED" to "联系人已屏蔽",
    "CONTACT UNBLOCKED" to "已取消屏蔽联系人",
    "REDUCED MOTION ENABLED" to "已开启减少动画",
    "REDUCED MOTION DISABLED" to "已关闭减少动画",
    "HIGH CONTRAST ENABLED" to "已开启高对比度",
    "HIGH CONTRAST DISABLED" to "已关闭高对比度",
    "CONNECTION TIMEOUT UPDATED" to "连接请求超时已更新",
    "CONTACT ORDER UPDATED" to "联系人排序已更新",
    "LOCAL CONTACTS AND CANVASES REMOVED" to "已删除本机联系人与画布",
    "ARCHIVE COULD NOT BE UNLOCKED" to "无法解锁归档",
    "ARCHIVE RESTORED LOCALLY" to "归档已恢复到本机",
    "BOTH PEOPLE MUST BE LIVE TO CLEAR" to "双方都在线时才能共同清空",
    "CLEAR APPROVED — WAITING FOR BOTH DEVICES" to "清空已批准，正在等待双方设备",
    "CLEAR REQUEST EXPIRED" to "清空请求已过期",
    "CLEAR REQUEST REJECTED" to "清空请求已拒绝",
    "CLEAR REQUEST SENT" to "清空请求已发送",
    "CLEAR REQUEST NOT SENT" to "清空请求未发送",
    "CONTACT ALREADY PAIRED" to "该联系人已经配对",
    "CONTACT PAIRED" to "联系人已配对",
    "CONTACT PAIRED — VERIFY SAFETY CODE" to "联系人已配对，请核对安全码",
    "INVALID INVITE" to "邀请码无效",
    "INVITE EXPIRED" to "邀请码已过期",
    "NEW SERVER FAILED PROTOCOL TEST" to "新服务器未通过兼容性测试",
    "NO RESPONSE" to "对方没有响应",
    "NO SERVER ROLLBACK AVAILABLE" to "没有可回退的服务器",
    "REQUEST DECLINED" to "连接请求被拒绝",
    "SAFETY CODE VERIFIED" to "安全码已验证",
    "SERVER ADDRESS UPDATED" to "服务器地址已更新",
    "SERVER MIGRATION STARTED" to "服务器迁移已开始",
    "SERVER ROLLBACK STARTED" to "服务器回退已开始",
    "SPACE CLEARED — UNDO AVAILABLE" to "空间已清空，可以撤销",
    "SPACE RESTORED" to "空间已恢复",
    "TESTING NEW SERVER" to "正在测试新服务器",
    "THIS SERVER IS ALREADY ACTIVE" to "当前已经在使用此服务器",
    "UNDO WINDOW ENDED" to "撤销时间已结束",
    "VERIFY SAFETY CODE BEFORE CONNECTING" to "连接前请先核对安全码",
    "WAIT FOR CURRENT SYNC BEFORE MIGRATING" to "请等待当前同步完成后再迁移",
    "CAN'T REACH PRIVATE SERVER" to "无法连接私人服务器",
    "ENCRYPTED ARCHIVE SAVED" to "加密归档已保存",
    "EXPORT NOT CREATED" to "导出未生成",
    "IMAGE SAVED" to "图片已保存",
    "PASSWORD MUST BE AT LEAST 8 CHARACTERS" to "密码至少需要 8 个字符",
    "PDF SAVED" to "PDF 已保存",
    "RESTORE FROM CONTACTS SETTINGS" to "请从联系人设置恢复归档",
    "APP LOCK ENABLED" to "应用锁已开启",
    "APP LOCK DISABLED" to "应用锁已关闭",
    "SCREENSHOTS BLOCKED" to "已阻止截屏",
    "SCREENSHOTS ALLOWED" to "已允许截屏",
    "GENERIC NOTIFICATIONS ENABLED" to "通用通知已开启",
    "NOTIFICATIONS DISABLED" to "通知已关闭",
    "UNBLOCK CONTACT BEFORE CONNECTING" to "请先取消屏蔽再连接",
    "WSS REQUIRED" to "正式版本必须使用 WSS 安全连接",
    "INVALID SERVER ADDRESS" to "服务器地址无效",
    "BLOCK COPIED TO PRIVATE SPACE" to "气泡已复制到私人空间",
    "CANCEL" to "取消",
    "HIDDEN INPUT" to "隐藏输入",
    "ONLY VISIBLE ON THIS DEVICE" to "仅本设备可见",
    "Write privately, then reveal it as one change…" to "先私密输入，再作为一次修改公开…",
    "REVEAL" to "公开",
    "DISCARD" to "丢弃",
    "KEEP DRAFT" to "保留草稿",
    "EXPORT SPACE" to "导出空间",
    "ENCRYPTED ARCHIVE" to "加密归档",
    "IMAGE" to "图片",
    "PRIVATE SPACE" to "私人空间",
    "END LIVE SESSION" to "结束实时会话",
    "BACK TO CONTACTS" to "返回联系人",
    "MERGE BLOCK" to "合并气泡",
    "Create another block before merging." to "请先创建另一个气泡。",
    "Choose the target block. Content will join at a paragraph boundary." to "选择目标气泡，内容将按段落合并。",
    "EMPTY BLOCK" to "空气泡",
    "BLOCK DELETED — UNDO" to "气泡已删除",
    "BLOCK RESTORED" to "气泡已恢复",
    "BLOCKS MERGED" to "气泡已合并",
    "BLOCK UNGROUPED" to "气泡已脱组",
    "2 LIVE" to "2 人在线",
)

@Composable
fun ui(english: String, chinese: String = chineseUi[english] ?: english): String =
    if (LocalUiLanguage.current == UiLanguage.Chinese) chinese else english
